apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ha-hello-world
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{.name}}-ha-hello-world'
    spec:
      project: default
      source:
        repoURL: https://github.com/josepperna/cluster-with-gitops.git
        targetRevision: main 
        path: argocd/apps/cert-manager
      destination:
        server: '{{ .server }}'
        namespace: ha-hello-world
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
