apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{.name}}-ingress-nginx' # 'name' field of the Secret
    spec:
      project: default
      source:
        repoURL: https://github.com/kubernetes/ingress-nginx
        targetRevision: controller-v1.12.0  # Replace <version> with the specific version you want
        path: deploy/static/provider/cloud
      destination:
        server: '{{ .server }}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
